when:
  - evaluate: 'not (CI_COMMIT_MESSAGE contains "SKIPCI")'
  - event: pull_request

steps:
  - name: compile
    image: codeberg.org/ahappydeath/prompt-base:latest
    commands:
      - mix deps.get
      - mix compile --warnings-as-errors 
    when:
      - event: pull_request

  - name: check_formatted
    image: codeberg.org/ahappydeath/prompt-base:latest
    commands:
      - mix format --check-formatted
    when:
      - event: pull_request
 
  - name: graph_dependencies
    image: codeberg.org/ahappydeath/prompt-base:latest
    commands:
      - mix graph --fail-above 1
    when:
      - event: pull_request
